os:
  - linux
#  - osx Removing temporarily as homebrew does not link OpenSSL
# see https://github.com/Zewo/COpenSSL/issues/4
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install openssl;
      brew link --force openssl;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install libssl-dev;
    fi
script:
  - eval "$(curl -sL swift.qutheory.io/ci)"
  - eval "$(curl -sL swift.qutheory.io/codecov)"
notifications:
  slack: talkstormpath:kN559lSL73v5N6DQ796LRtwm